### ISSUE TITLE
url is labeled as optional in the documentation but required in the code

### ISSUE THREAD

**Issue by seiyria** [bluwy/release-for-reddit-action#1]
https://github.com/marketplace/actions/release-for-reddit#url

https://github.com/bluwy/release-for-reddit-action/blob/master/index.js#L27-L29

I'm not sure which it is, but it looks like url is also supposed to have a default which I don't see set in the code.

**Comment by bluwy** [comment]
The default value is actually set in https://github.com/bluwy/release-for-reddit-action/blob/master/action.yml, so when the `url` is not defined, it'll use the default value from there.

I've set the `getInput` to required so that it also catches if the `url` is set but to an empty string. It's a bit of a hack since I'm taking advantage on the GitHub's [`getInput` implementation](https://github.com/actions/toolkit/blob/9ad01e4fd30025e8858650d38e95cfe9193a3222/packages/core/src/core.ts#L62-L77) where it checks if the input is truthy before sending an error. But it works if it ever happens.

**Comment by seiyria** [comment]
That's interesting... So, [this is what I had](https://github.com/seiyria/Rasterkhann/blob/e2704685fad81e2fbf9a94ed583b9b2baad9199f/.github/workflows/release-tags.yml) when it failed for me recently. I've changed it to [this](https://github.com/seiyria/Rasterkhann/blob/main/.github/workflows/release-tags.yml) in an attempt to see if maybe it's doing something in the wrong order (have not tested this one yet). Is there any glaring issues you see with it?

**Comment by bluwy** [comment]
Yup. The latter version should be the right one. Since you're running the action on push, `${{ github.event.release.html_url }}` is undefined, so using the url from the release created from the `create_release` step should do the trick.

I also noticed that you may have provided a wrong subreddit name. Perhaps you are looking for the `title` option. Though make sure the subreddit name is also set to a valid one.

**Comment by seiyria** [comment]
Oh yikes, thanks for catching that. You're absolutely correct. And thanks! I'm a bit new to Actions but looking at it, the order of operations bit makes more sense now. Thanks again for the great plugin!
